# Composition for development

version: '2'

services:
  odoo:
    tty: true
    stdin_open: true
    build: ./odoo/
    command: ""
    ports:
      - 8069
      - 8072
    links:
      - db:db
    volumes:
      # volumes should be shared for dev only
      - "./odoo/src:/opt/odoo/src"
      - "./odoo/local-src:/opt/odoo/local-src"
      - "./odoo/external-src:/opt/odoo/external-src"
      - "./odoo/features:/opt/odoo/features"
      - "./odoo/data:/opt/odoo/data"
      - "data-odoo:/data/odoo"
    environment:
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=odoodb
      - ADMIN_PASSWD=# set me
      - RUNNING_ENV=dev
      - MARABUNTA_MODE=demo

  db:
    # could be camptocamp/postgis:9.5 if postgis is required
    image: postgres:9.5
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - "data-db:/var/lib/postgresql/data"
    expose:
      - 5432

  # can be useful for dev when longpolling is required
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - odoo:odoo

volumes:
  data-odoo:
  data-db:
